/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esoft;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class CashierPaymentView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CashierPaymentView
     */
    public CashierPaymentView() {
        initComponents();
        show_user();
    }
     public ArrayList<user> userList(){
        ArrayList<user> userList = new ArrayList<>();
        
         
         try
        {
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esoft","root","");
          String quary1="SELECT * FROM payments";
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery(quary1);
         user user;
         while(rs.next()){
             user=new user(rs.getInt("no"),rs.getString("id"),rs.getString("name"),rs.getString("programe"),rs.getString("year"),rs.getString("semester"),rs.getString("fee"));
             userList.add(user);
         }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
         return userList;
     }
       public void show_user(){
            ArrayList<user> list =userList();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           Object[]row = new Object[7];
            for(int i = 0;i<list.size(); i++){
                    row[0]=list.get(i).getno();
                    row[1]=list.get(i).getid();
                    row[2]=list.get(i).getname();
                    row[3]=list.get(i).getprograme();
                    row[4]=list.get(i).getyear();
                    row[5]=list.get(i).getsemester();
                    row[6]=list.get(i).getfee();
                    model.addRow(row);
            }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tableid = new javax.swing.JTextField();
        Tablename = new javax.swing.JTextField();
        Tableprograme = new javax.swing.JComboBox<>();
        Tableyear = new javax.swing.JComboBox<>();
        Tablesemester = new javax.swing.JComboBox<>();
        Tablefee = new javax.swing.JTextField();

        jPanel1.setPreferredSize(new java.awt.Dimension(890, 460));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no", "Id", "Name", "Programe", "Year", "Semester", "fee"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NAME");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PROGRAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("YEAR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SEMESTER");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("FEE");

        Tableid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableid.setForeground(new java.awt.Color(255, 0, 0));

        Tablename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablename.setForeground(new java.awt.Color(255, 0, 0));

        Tableprograme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableprograme.setForeground(new java.awt.Color(255, 0, 0));
        Tableprograme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web Engineering", "Software Engineering", "English", "Hardware Engineering", "Network Engineering", "Graphic Design" }));

        Tableyear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableyear.setForeground(new java.awt.Color(255, 0, 0));
        Tableyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST YEAR", "2ND YEAR", "3RD YEAR", "4TH YEAR" }));

        Tablesemester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablesemester.setForeground(new java.awt.Color(255, 0, 0));
        Tablesemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST SEMESTER", "2ND SEMESTER", "3RD SEMESTER" }));

        Tablefee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablefee.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tableprograme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tableid)
                    .addComponent(Tablename)
                    .addComponent(Tablefee)
                    .addComponent(Tablesemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tableyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tableid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Tablename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Tableprograme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tableyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tablesemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tablefee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int i = jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        
        Tableid.setText(model.getValueAt(i,1).toString());
        Tablename.setText(model.getValueAt(i,2).toString());
        Tablefee.setText(model.getValueAt(i,6).toString());
       
       
        String programe1=model.getValueAt(i,3).toString();
           switch(programe1){
               case "Web Engineering":
                   Tableprograme.setSelectedIndex(0);
                   break;
               case "Software Engineering":
                   Tableprograme.setSelectedIndex(1);
                   break;
               case "English":
                   Tableprograme.setSelectedIndex(2);
                   break;
               case "Hardware Engineering":
                   Tableprograme.setSelectedIndex(3);
                   break;
                case "Network Engineering":
                   Tableprograme.setSelectedIndex(4);
                   break;
                case "Graphic Design":
                   Tableprograme.setSelectedIndex(5);
                   break;
           }
           
        String Year1=model.getValueAt(i,4).toString();
            switch(Year1){
               case"1ST YEAR":
                    Tableyear.setSelectedIndex(0);
                    break;
               case"2ND YEAR":
                    Tableyear.setSelectedIndex(1);
                    break;
               case"3RD YEAR":
                    Tableyear.setSelectedIndex(2);
                    break;
            }
         String semester1=model.getValueAt(i,5).toString();
            switch(semester1){
                case"1ST SEMESTER":
                    Tablesemester.setSelectedIndex(0);
                    break;
                case"2ND SEMESTER":
                    Tablesemester.setSelectedIndex(1);
                    break;
                case"3RD SEMESTER":
                    Tablesemester.setSelectedIndex(2);
                    break;
                    
            }        
       
            
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tablefee;
    private javax.swing.JTextField Tableid;
    private javax.swing.JTextField Tablename;
    private javax.swing.JComboBox<String> Tableprograme;
    private javax.swing.JComboBox<String> Tablesemester;
    private javax.swing.JComboBox<String> Tableyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
