/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esoft;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author USER
 */
public class CashierUpdatePayment extends javax.swing.JInternalFrame {

    /**
     * Creates new form CashierUpdatePayment
     */
    public CashierUpdatePayment() {
        initComponents();
        show_user();
        
    }
     public ArrayList<user> userList(){
        ArrayList<user> userList = new ArrayList<>();
        
         
         try
        {
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esoft","root","");
          String quary1="SELECT * FROM payments";
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery(quary1);
         user user;
         while(rs.next()){
             user=new user(rs.getInt("no"),rs.getString("id"),rs.getString("name"),rs.getString("programe"),rs.getString("year"),rs.getString("semester"),rs.getString("fee"));
             userList.add(user);
         }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
         return userList;
     }
       public void show_user(){
            ArrayList<user> list =userList();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           Object[]row = new Object[7];
            for(int i = 0;i<list.size(); i++){
                
                    row[0]=list.get(i).getno();
                    row[1]=list.get(i).getid();
                    row[2]=list.get(i).getname();
                    row[3]=list.get(i).getprograme();
                    row[4]=list.get(i).getyear();
                    row[5]=list.get(i).getsemester();
                    row[6]=list.get(i).getfee();
                    model.addRow(row);
            }
       }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Tableid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tablename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tableprograme = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Tableyear = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Tablesemester = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Tablefee = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1047, 470));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sno", "Id", "Name", "Programe", "Year", "Semester", "fee"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        Tableid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableid.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("NAME");

        Tablename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablename.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PROGRAME");

        Tableprograme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableprograme.setForeground(new java.awt.Color(255, 0, 0));
        Tableprograme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web Engineering", "Software Engineering", "English", "Hardware Engineering", "Network Engineering", "Graphic Design", " " }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("YEAR");

        Tableyear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tableyear.setForeground(new java.awt.Color(255, 0, 0));
        Tableyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST YEAR", "2ND YEAR", "3RD YEAR", "4TH YEAR" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("SEMESTER");

        Tablesemester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablesemester.setForeground(new java.awt.Color(255, 0, 0));
        Tablesemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ST SEMESTER", "2ND SEMESTER", "3RD SEMESTER" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("FEE");

        Tablefee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tablefee.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tablefee, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tableyear, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tableprograme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tablename, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tableid, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tablesemester, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tableid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tablename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tableprograme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tableyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tablesemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tablefee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

         int i = jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        
        Tableid.setText(model.getValueAt(i,1).toString());
        Tablename.setText(model.getValueAt(i,2).toString());
        Tablefee.setText(model.getValueAt(i,6).toString());
       
       
        String programe1=model.getValueAt(i,3).toString();
           switch(programe1){
               case "Web Engineering":
                   Tableprograme.setSelectedIndex(0);
                   break;
               case "Software Engineering":
                   Tableprograme.setSelectedIndex(1);
                   break;
               case "English":
                   Tableprograme.setSelectedIndex(2);
                   break;
               case "Hardware Engineering":
                   Tableprograme.setSelectedIndex(3);
                   break;
                case "Network Engineering":
                   Tableprograme.setSelectedIndex(4);
                   break;
                case "Graphic Design":
                   Tableprograme.setSelectedIndex(5);
                   break;
           }
           
        String Year1=model.getValueAt(i,4).toString();
            switch(Year1){
               case"1ST YEAR":
                    Tableyear.setSelectedIndex(0);
                    break;
               case"2ND YEAR":
                    Tableyear.setSelectedIndex(1);
                    break;
               case"3RD YEAR":
                    Tableyear.setSelectedIndex(2);
                    break;
            }
         String semester1=model.getValueAt(i,5).toString();
            switch(semester1){
                case"1ST SEMESTER":
                    Tablesemester.setSelectedIndex(0);
                    break;
                case"2ND SEMESTER":
                    Tablesemester.setSelectedIndex(1);
                    break;
                case"3RD SEMESTER":
                    Tablesemester.setSelectedIndex(2);
                    break;
                    
            }        
       
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
            
         try
        {
          Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/esoft","root","");
          int row=jTable1.getSelectedRow();
          String value=(jTable1.getModel().getValueAt(row, 0).toString());
         String query="UPDATE payments SET id=?,name=?,programe=?,year=?,semester=?,fee=? where no= "+value;
          PreparedStatement pst = con.prepareStatement(query);
          pst.setString(1,Tableid.getText());
          pst.setString(2,Tablename.getText());
          pst.setString(6,Tablefee.getText());
          
          String progra;
          progra=Tableprograme.getSelectedItem().toString();
          pst.setString(3,progra);
          
          String yer;
          yer=Tableyear.getSelectedItem().toString();
          pst.setString(4,yer);
          
          String sem;
          sem=Tablesemester.getSelectedItem().toString();
          pst.setString(5,sem);
          
          
          pst.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
          show_user();
         
          JOptionPane.showMessageDialog(null, "Update Sucessfully");
          
              
        Tableid.setText("");
        Tablename.setText("");
        Tablefee.setText("");
        
        Tableprograme.setSelectedIndex(0);
        Tableyear.setSelectedIndex(0);
        Tablesemester.setSelectedIndex(0);
        }
          catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tablefee;
    private javax.swing.JTextField Tableid;
    private javax.swing.JTextField Tablename;
    private javax.swing.JComboBox<String> Tableprograme;
    private javax.swing.JComboBox<String> Tablesemester;
    private javax.swing.JComboBox<String> Tableyear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
